name: Go Build & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Download Dependencies
      run: go mod download
      
    - name: Build Application
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/image-downloader-linux-amd64 main.go
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o build/image-downloader-windows-amd64.exe main.go
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o build/image-downloader-darwin-amd64 main.go

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: releases
        path: build/
